import ROLES from "./roles";

const QUOTAS = {
  [ROLES.DIRECTEUR]: 8,
  [ROLES.CO_DIRECTEUR]: 8,
  [ROLES.CADRE_SANTE]: 10,
  [ROLES.CHEF_DE_SERVICE]: 12,
  [ROLES.MEDECIN_CHEF]: 12,
  [ROLES.MEDECIN]: 15,
  [ROLES.INTERNE]: 15,
  [ROLES.INFIRMIER]: 15,
  [ROLES.AMBULANCIER]: 15,
  [ROLES.STAGIAIRE]: 15,
};

export default QUOTAS;
