export enum TicketType {
  _Recruitment = "support_recruitment",
  _Support = "support_support",
  _Complaint = "support_complaint",
  _Partnership = "support_partnership",
  _Suggestion = "support_suggestion",
  _PPA = "meeting_ppa",
  _Psychology = "meeting_psychology",
  _Toxicology = "meeting_toxicology",
  _Surgery = "meeting_surgery",
  _Gynecology = "meeting_gynecology",
  _Radiography = "meeting_radiography",
  _HumanResources = "meeting_human_resources",
  _Events = "meeting_events",
}
